/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Apr  8 15:36:42 2016
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void ACC_Logic_Outputs_wrapper(const boolean_T *en_man,
                          const real32_T *s,
                          const real32_T *u,
                          const real32_T *H,
                          boolean_T *en_vel,
                          boolean_T *en_pos,
                          real32_T *lead_s,
                          real32_T *lead_us)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      y0[0] = u0[0]; 
 For complex signals use: y0[0].re = u0[0].re; 
      y0[0].im = u0[0].im;
      y1[0].re = u1[0].re;
      y1[0].im = u1[0].im;
*/

int lead_car_i = 0;
int i;
int s_temp = 3000;

for(i = 1; i < 7; ++i)
{
    if(s[i] > s[0] && s[i] < s_temp)
    {
        lead_car_i = i;  
        s_temp = s[i];
    }
}

if(lead_car_i == 0)
{
    en_vel[0] = true;
    en_pos[0] = false;
}
else
{
    if(u[lead_car_i] <= u[0] &&
            s[lead_car_i] - s[0] <= H[0])
    {
        en_vel[0] = false;
        en_pos[0] = true;
    }
//    else if(s[lead_car_i] != s[0])
//    {
//        en_vel[0] = false;
//        en_pos[0] = true;
//    }
    else
    {
        en_vel[0] = true;
        en_pos[0] = false;
    }
}

lead_s[0] = s[lead_car_i];
lead_us[0] = u[lead_car_i];

if(en_man[0])
{
    en_vel[0] = false;
    en_pos[0] = false;
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
